version: "3.7"

networks:
  default:
    attachable: "true"
    name: "neko-rooms-traefik"

services:
  traefik:
    image: "traefik:2.4"
    restart: "always"
    environment:
      - "TZ=Europe/Vienna"
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms-traefik"
      - "--entrypoints.websecure.address=:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "172.17.0.1:7097:8080"

  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "always"
    environment:
      - "TZ=Europe/Vienna"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=${IP}"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN=${DOMAIN}"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT=websecure"
      - "NEKO_ROOMS_TRAEFIK_NETWORK=neko-rooms-traefik"
      - "NEKO_ROOMS_STORAGE_ENABLED=true"
      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"
      - "NEKO_ROOMS_STORAGE_EXTERNAL=/opt/app/${PIPELINE_NAME}/neko-data"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./neko-data:/data
      - ./neko-data:/var/lib/docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=websecure"
      - "traefik.http.routers.neko-rooms.rule=Host(`${DOMAIN}`)"